package io.github.chains_project.theo.preprocessor;

import picocli.CommandLine;

import java.nio.file.Path;

/**
 * This class represents the main entry point to the preprocessor.
 */
public class Main {

    public static void main(String[] args) {
        int exitCode = new CommandLine(new PreProcess()).execute(args);
        System.exit(exitCode);
    }

    @CommandLine.Command(name = "preprocess", mixinStandardHelpOptions = true, version = "0.1")
    private static class PreProcess implements Runnable {

        @CommandLine.Option(
                names = {"-p", "--pomfile"},
                paramLabel = "POMFILE",
                description = "The path to the pom file of the project. In case of a multi module project, add the pom "
                        + "file corresponding to the executable jar",
                required = true
        )
        Path pomfile;

        @CommandLine.Option(
                names = {"-l", "--lockfile"},
                paramLabel = "LOCKFILE",
                description = "The path to the lockfile generated by the maven-lockfile",
                required = true
        )
        Path lockfile;

        @Override
        public void run() {
            DependencyPreProcessor preProcessor = new DependencyPreProcessor();
            preProcessor.processPomFile(pomfile, lockfile);
        }
    }
}